import json
from pathlib import Path
from typing import List
from .models import NameEntry


NAMES_DATA = [
    {"name": "团子", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["shy", "gentle"], "meaning": "圆滚滚的可爱模样", "popularity": 9},
    {"name": "棉花糖", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["gentle", "sweet"], "coat_colors": ["white", "cream"], "meaning": "像棉花糖一样柔软甜美", "popularity": 8},
    {"name": "小橘", "language": "zh", "style": "cute", "species": ["cat"], "gender": ["neutral"], "personality": ["playful", "energetic"], "coat_colors": ["orange", "ginger"], "meaning": "橙色毛发的小可爱", "popularity": 9},
    {"name": "奶牛", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["playful"], "coat_colors": ["black-white"], "meaning": "黑白花纹像奶牛", "popularity": 7},
    {"name": "豆沙包", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["chubby", "gentle"], "coat_colors": ["brown", "gray"], "meaning": "圆滚滚像豆沙包", "popularity": 7},
    {"name": "雪球", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["gentle", "playful"], "coat_colors": ["white"], "meaning": "像雪球一样洁白", "popularity": 8},
    {"name": "毛毛", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["fluffy", "gentle"], "meaning": "毛茸茸的小可爱", "popularity": 8},
    {"name": "乖乖", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["obedient", "gentle"], "meaning": "乖巧听话的宝贝", "popularity": 7},
    {"name": "跳跳", "language": "zh", "style": "cute", "species": ["rabbit", "dog"], "gender": ["neutral"], "personality": ["energetic", "playful"], "meaning": "爱蹦蹦跳跳的小家伙", "popularity": 6},
    {"name": "奶茶", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["brown", "cream"], "meaning": "像奶茶一样温暖甜美", "popularity": 9},
    {"name": "布丁", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["yellow", "cream"], "meaning": "像布丁一样Q弹可爱", "popularity": 8},
    {"name": "可乐", "language": "zh", "style": "cute", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["energetic", "playful"], "meaning": "像可乐一样充满活力", "popularity": 8},
    {"name": "薯条", "language": "zh", "style": "cute", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["playful", "silly"], "meaning": "可爱的食物名", "popularity": 7},
    {"name": "汉堡", "language": "zh", "style": "cute", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["chubby", "playful"], "meaning": "圆滚滚像汉堡", "popularity": 6},
    {"name": "饺子", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["chubby", "gentle"], "coat_colors": ["white", "cream"], "meaning": "圆滚滚像饺子", "popularity": 7},
    {"name": "元宵", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["white"], "meaning": "像元宵一样团圆可爱", "popularity": 6},
    {"name": "月饼", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["brown", "yellow"], "meaning": "像月饼一样圆满", "popularity": 6},
    {"name": "汤圆", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["white"], "meaning": "像汤圆一样圆滚滚", "popularity": 7},

    {"name": "豆豆", "language": "zh", "style": "traditional", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["small", "energetic"], "min_age_months": 0, "max_age_months": 24, "meaning": "像豆子一样小巧可爱", "popularity": 8},
    {"name": "多多", "language": "zh", "style": "traditional", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["energetic", "playful"], "meaning": "福气多多", "popularity": 8},
    {"name": "来福", "language": "zh", "style": "traditional", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["loyal", "gentle"], "meaning": "带来福气", "popularity": 7},
    {"name": "招财", "language": "zh", "style": "traditional", "species": ["cat"], "gender": ["neutral"], "personality": ["gentle", "calm"], "meaning": "招财进宝", "popularity": 8},
    {"name": "进宝", "language": "zh", "style": "traditional", "species": ["cat", "dog"], "gender": ["male", "neutral"], "personality": ["gentle"], "meaning": "招财进宝", "popularity": 6},
    {"name": "旺财", "language": "zh", "style": "traditional", "species": ["dog"], "gender": ["male", "neutral"], "personality": ["loyal", "energetic"], "meaning": "兴旺财运", "popularity": 8},
    {"name": "福宝", "language": "zh", "style": "traditional", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["gentle", "sweet"], "meaning": "福气宝贝", "popularity": 7},
    {"name": "吉祥", "language": "zh", "style": "traditional", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["gentle", "calm"], "meaning": "吉祥如意", "popularity": 7},
    {"name": "如意", "language": "zh", "style": "traditional", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["gentle", "sweet"], "meaning": "万事如意", "popularity": 7},
    {"name": "平安", "language": "zh", "style": "traditional", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["calm", "gentle"], "meaning": "平平安安", "popularity": 6},
    {"name": "乐乐", "language": "zh", "style": "traditional", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["happy", "energetic"], "meaning": "快快乐乐", "popularity": 8},
    {"name": "欢欢", "language": "zh", "style": "traditional", "species": ["dog", "cat"], "gender": ["female", "neutral"], "personality": ["happy", "playful"], "meaning": "欢欢喜喜", "popularity": 7},
    {"name": "贝贝", "language": "zh", "style": "traditional", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["gentle", "sweet"], "meaning": "宝贝", "popularity": 8},
    {"name": "宝宝", "language": "zh", "style": "traditional", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["gentle"], "min_age_months": 0, "max_age_months": 12, "meaning": "小宝宝", "popularity": 8},
    {"name": "妞妞", "language": "zh", "style": "traditional", "species": ["dog", "cat"], "gender": ["female"], "personality": ["sweet", "gentle"], "meaning": "可爱的小女孩", "popularity": 7},

    {"name": "Lucky", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["happy", "gentle"], "meaning": "幸运的", "popularity": 9},
    {"name": "Sunny", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["happy", "energetic"], "coat_colors": ["yellow", "orange", "golden"], "meaning": "阳光灿烂", "popularity": 9},
    {"name": "Shadow", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["quiet", "calm"], "coat_colors": ["black", "gray"], "meaning": "影子", "popularity": 7},
    {"name": "Angel", "language": "en", "style": "western", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["gentle", "sweet"], "coat_colors": ["white"], "meaning": "天使", "popularity": 8},
    {"name": "Coco", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["sweet", "playful"], "coat_colors": ["brown", "chocolate"], "meaning": "可可，甜美可爱", "popularity": 9},
    {"name": "Milo", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["playful", "energetic"], "meaning": "可爱的名字", "popularity": 8},
    {"name": "Bella", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["female"], "personality": ["gentle", "sweet"], "meaning": "美丽的", "popularity": 9},
    {"name": "Max", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["male"], "personality": ["strong", "energetic"], "meaning": "最大的，强壮的", "popularity": 9},
    {"name": "Charlie", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["friendly", "loyal"], "meaning": "自由人", "popularity": 8},
    {"name": "Lucy", "language": "en", "style": "western", "species": ["cat", "dog"], "gender": ["female"], "personality": ["sweet", "gentle"], "meaning": "光，带来光明的", "popularity": 8},
    {"name": "Daisy", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["female"], "personality": ["sweet", "happy"], "coat_colors": ["white", "yellow"], "meaning": "雏菊", "popularity": 7},
    {"name": "Rocky", "language": "en", "style": "western", "species": ["dog"], "gender": ["male"], "personality": ["strong", "energetic"], "meaning": "岩石，坚强的", "popularity": 7},
    {"name": "Molly", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["female"], "personality": ["gentle", "sweet"], "meaning": "海的女儿", "popularity": 7},
    {"name": "Buddy", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["friendly", "loyal"], "meaning": "好朋友，伙伴", "popularity": 8},
    {"name": "Princess", "language": "en", "style": "western", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "sweet"], "meaning": "公主", "popularity": 7},
    {"name": "Prince", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["male"], "personality": ["gentle", "noble"], "meaning": "王子", "popularity": 6},
    {"name": "Snowball", "language": "en", "style": "western", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["gentle", "playful"], "coat_colors": ["white"], "meaning": "雪球", "popularity": 7},
    {"name": "Peanut", "language": "en", "style": "western", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["small", "energetic"], "min_age_months": 0, "max_age_months": 12, "meaning": "花生，小巧可爱", "popularity": 7},

    {"name": "大白", "language": "zh", "style": "cool", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["gentle", "protective"], "coat_colors": ["white"], "meaning": "超能陆战队中的大白，温暖守护", "popularity": 8},
    {"name": "闪电", "language": "zh", "style": "cool", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["energetic", "fast"], "meaning": "像闪电一样快", "popularity": 7},
    {"name": "雷神", "language": "zh", "style": "cool", "species": ["dog"], "gender": ["male"], "personality": ["strong", "brave"], "meaning": "北欧神话中的雷神", "popularity": 6},
    {"name": "钢铁侠", "language": "zh", "style": "cool", "species": ["dog", "cat"], "gender": ["male"], "personality": ["brave", "energetic"], "meaning": "超级英雄", "popularity": 6},
    {"name": "黑武士", "language": "zh", "style": "cool", "species": ["dog", "cat"], "gender": ["male"], "personality": ["calm", "mysterious"], "coat_colors": ["black"], "meaning": "星球大战黑武士", "popularity": 5},
    {"name": "悟空", "language": "zh", "style": "cool", "species": ["dog", "cat"], "gender": ["male"], "personality": ["energetic", "brave"], "meaning": "齐天大圣孙悟空", "popularity": 7},
    {"name": "哪吒", "language": "zh", "style": "cool", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["energetic", "playful"], "min_age_months": 0, "max_age_months": 24, "meaning": "神话中的小英雄", "popularity": 6},
    {"name": "哈利", "language": "zh", "style": "cool", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["brave", "smart"], "meaning": "哈利波特", "popularity": 7},
    {"name": "洛基", "language": "zh", "style": "cool", "species": ["cat", "dog"], "gender": ["male"], "personality": ["mischievous", "smart"], "meaning": "北欧神话中的恶作剧之神", "popularity": 5},
    {"name": "黑豹", "language": "zh", "style": "cool", "species": ["cat", "dog"], "gender": ["male"], "personality": ["strong", "calm"], "coat_colors": ["black"], "meaning": "超级英雄黑豹", "popularity": 5},
    {"name": "金刚", "language": "zh", "style": "cool", "species": ["dog"], "gender": ["male"], "personality": ["strong", "protective"], "meaning": "强大的金刚", "popularity": 5},
    {"name": "小虎", "language": "zh", "style": "cool", "species": ["cat", "dog"], "gender": ["male", "neutral"], "personality": ["brave", "energetic"], "coat_colors": ["orange", "striped"], "min_age_months": 0, "max_age_months": 24, "meaning": "像小老虎一样威猛", "popularity": 7},
    {"name": "龙飞", "language": "zh", "style": "cool", "species": ["dog"], "gender": ["male"], "personality": ["strong", "energetic"], "meaning": "龙飞凤舞，充满活力", "popularity": 5},
    {"name": "凤凰", "language": "zh", "style": "cool", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["noble", "gentle"], "coat_colors": ["red", "orange"], "meaning": "浴火重生的神鸟", "popularity": 5},
    {"name": "麒麟", "language": "zh", "style": "cool", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["noble", "gentle"], "meaning": "祥瑞神兽", "popularity": 4},

    {"name": "墨墨", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["calm", "smart"], "coat_colors": ["black", "gray"], "meaning": "书香墨韵，文雅", "popularity": 6},
    {"name": "砚砚", "language": "zh", "style": "literary", "species": ["cat"], "gender": ["neutral"], "personality": ["calm", "gentle"], "coat_colors": ["black", "gray"], "meaning": "文房四宝之砚台", "popularity": 5},
    {"name": "竹竹", "language": "zh", "style": "literary", "species": ["cat", "rabbit"], "gender": ["neutral"], "personality": ["gentle", "quiet"], "meaning": "竹子，高洁清雅", "popularity": 5},
    {"name": "兰兰", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "sweet"], "meaning": "兰花，高洁典雅", "popularity": 5},
    {"name": "梅梅", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["strong", "gentle"], "coat_colors": ["white", "gray"], "meaning": "梅花，傲雪凌霜", "popularity": 5},
    {"name": "菊菊", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["gentle"], "coat_colors": ["yellow", "orange"], "meaning": "菊花，清雅高洁", "popularity": 4},
    {"name": "清风", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["calm", "gentle"], "meaning": "清风明月，闲适自在", "popularity": 5},
    {"name": "明月", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["calm", "gentle"], "coat_colors": ["white", "silver"], "meaning": "明月皎皎", "popularity": 6},
    {"name": "星辰", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["mysterious", "calm"], "coat_colors": ["black", "gray"], "meaning": "星辰大海", "popularity": 6},
    {"name": "云朵", "language": "zh", "style": "literary", "species": ["cat", "dog", "rabbit"], "gender": ["female", "neutral"], "personality": ["gentle", "fluffy"], "coat_colors": ["white", "cream"], "meaning": "洁白的云朵", "popularity": 7},
    {"name": "烟雨", "language": "zh", "style": "literary", "species": ["cat"], "gender": ["female"], "personality": ["gentle", "shy"], "coat_colors": ["gray", "blue-gray"], "meaning": "烟雨朦胧，柔美", "popularity": 4},
    {"name": "山水", "language": "zh", "style": "literary", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["calm", "strong"], "meaning": "山水之间，宁静致远", "popularity": 4},
    {"name": "诗意", "language": "zh", "style": "literary", "species": ["cat"], "gender": ["female"], "personality": ["gentle", "sweet"], "meaning": "充满诗意", "popularity": 4},
    {"name": "画意", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["gentle", "creative"], "meaning": "如诗如画", "popularity": 4},
    {"name": "雅雅", "language": "zh", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "noble"], "meaning": "温文尔雅", "popularity": 5},

    {"name": "Luna", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["mysterious", "calm"], "coat_colors": ["black", "gray"], "meaning": "月亮女神", "popularity": 8},
    {"name": "Stella", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["bright", "gentle"], "meaning": "星星，闪耀", "popularity": 7},
    {"name": "Aurora", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["mysterious", "gentle"], "coat_colors": ["multi-color"], "meaning": "极光，绚丽多彩", "popularity": 6},
    {"name": "Athena", "language": "en", "style": "literary", "species": ["dog", "cat"], "gender": ["female"], "personality": ["smart", "brave"], "meaning": "智慧女神雅典娜", "popularity": 6},
    {"name": "Zeus", "language": "en", "style": "cool", "species": ["dog"], "gender": ["male"], "personality": ["strong", "noble"], "meaning": "众神之王宙斯", "popularity": 6},
    {"name": "Odin", "language": "en", "style": "cool", "species": ["dog", "cat"], "gender": ["male"], "personality": ["wise", "strong"], "meaning": "北欧神话中的众神之王", "popularity": 5},
    {"name": "Freya", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "noble"], "meaning": "北欧女神", "popularity": 5},
    {"name": "Phoenix", "language": "en", "style": "cool", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["strong", "mysterious"], "coat_colors": ["red", "orange"], "meaning": "凤凰，浴火重生", "popularity": 6},
    {"name": "Sage", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["wise", "calm"], "meaning": "圣人，智者", "popularity": 5},
    {"name": "Willow", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "graceful"], "meaning": "柳树，柔美", "popularity": 5},
    {"name": "River", "language": "en", "style": "literary", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["calm", "flowing"], "meaning": "河流，宁静", "popularity": 5},
    {"name": "Sky", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["free", "calm"], "coat_colors": ["blue-gray", "gray"], "meaning": "天空，自由", "popularity": 6},
    {"name": "Ocean", "language": "en", "style": "literary", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["calm", "deep"], "coat_colors": ["blue", "gray"], "meaning": "海洋，深邃", "popularity": 5},
    {"name": "Echo", "language": "en", "style": "literary", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["gentle", "quiet"], "meaning": "回声，轻柔", "popularity": 5},
    {"name": "Mystic", "language": "en", "style": "literary", "species": ["cat"], "gender": ["neutral"], "personality": ["mysterious", "calm"], "coat_colors": ["black", "gray"], "meaning": "神秘的", "popularity": 4},

    {"name": "小不点", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["small", "energetic"], "min_age_months": 0, "max_age_months": 12, "meaning": "小小的可爱宝贝", "popularity": 7},
    {"name": "小天使", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["white"], "meaning": "像小天使一样可爱", "popularity": 7},
    {"name": "小可爱", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "meaning": "可爱的小家伙", "popularity": 7},
    {"name": "小甜心", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["sweet", "gentle"], "meaning": "甜蜜的小心肝", "popularity": 6},
    {"name": "小暖男", "language": "zh", "style": "cute", "species": ["dog", "cat"], "gender": ["male"], "personality": ["gentle", "sweet"], "meaning": "温暖的小男孩", "popularity": 6},
    {"name": "小淑女", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "noble"], "meaning": "文静的小淑女", "popularity": 6},
    {"name": "小顽皮", "language": "zh", "style": "cute", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["playful", "mischievous"], "min_age_months": 0, "max_age_months": 24, "meaning": "顽皮的小家伙", "popularity": 6},
    {"name": "小懒虫", "language": "zh", "style": "cute", "species": ["cat"], "gender": ["neutral"], "personality": ["lazy", "calm"], "meaning": "爱睡觉的小家伙", "popularity": 6},
    {"name": "小馋猫", "language": "zh", "style": "cute", "species": ["cat"], "gender": ["neutral"], "personality": ["food-motivated"], "meaning": "贪吃的小猫", "popularity": 5},
    {"name": "小迷糊", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["clumsy", "gentle"], "meaning": "迷迷糊糊的小可爱", "popularity": 5},
    {"name": "小机灵", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["smart", "energetic"], "meaning": "机灵的小家伙", "popularity": 6},
    {"name": "小勇敢", "language": "zh", "style": "cute", "species": ["dog", "cat"], "gender": ["male", "neutral"], "personality": ["brave", "energetic"], "meaning": "勇敢的小家伙", "popularity": 5},
    {"name": "小温柔", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["gentle", "sweet"], "meaning": "温柔的小家伙", "popularity": 6},
    {"name": "小活泼", "language": "zh", "style": "cute", "species": ["dog", "rabbit"], "gender": ["neutral"], "personality": ["energetic", "playful"], "meaning": "活泼的小家伙", "popularity": 5},
    {"name": "小安静", "language": "zh", "style": "cute", "species": ["cat", "rabbit"], "gender": ["neutral"], "personality": ["calm", "quiet"], "meaning": "安静的小家伙", "popularity": 5},

    {"name": "甜甜", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["sweet", "gentle"], "meaning": "甜甜的小可爱", "popularity": 7},
    {"name": "蜜蜜", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["sweet", "gentle"], "meaning": "像蜂蜜一样甜", "popularity": 6},
    {"name": "糖糖", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["female", "neutral"], "personality": ["sweet", "gentle"], "meaning": "像糖果一样甜", "popularity": 8},
    {"name": "果果", "language": "zh", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["sweet", "energetic"], "coat_colors": ["red", "green", "yellow"], "meaning": "甜甜的水果", "popularity": 7},
    {"name": "柠柠", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["energetic", "fresh"], "coat_colors": ["yellow", "orange"], "meaning": "柠檬，清新活力", "popularity": 5},
    {"name": "桃桃", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["pink", "cream"], "meaning": "水蜜桃，甜美", "popularity": 7},
    {"name": "樱樱", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "sweet"], "coat_colors": ["pink", "white"], "meaning": "樱花，柔美", "popularity": 6},
    {"name": "莉莉", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "pure"], "coat_colors": ["white"], "meaning": "百合花，纯洁", "popularity": 6},
    {"name": "玫玫", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female"], "personality": ["noble", "gentle"], "coat_colors": ["red", "pink"], "meaning": "玫瑰，高贵", "popularity": 5},
    {"name": "茉莉", "language": "zh", "style": "cute", "species": ["cat", "dog"], "gender": ["female"], "personality": ["gentle", "sweet"], "coat_colors": ["white"], "meaning": "茉莉花，清香", "popularity": 6},

    {"name": "Boots", "language": "en", "style": "cute", "species": ["cat"], "gender": ["neutral"], "personality": ["playful"], "coat_colors": ["black-white", "white-paws"], "meaning": "穿靴子的猫", "popularity": 6},
    {"name": "Whiskers", "language": "en", "style": "cute", "species": ["cat"], "gender": ["neutral"], "personality": ["curious", "playful"], "meaning": "胡须，可爱的猫", "popularity": 7},
    {"name": "Paws", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["gentle", "playful"], "meaning": "小爪子", "popularity": 6},
    {"name": "Fluffy", "language": "en", "style": "cute", "species": ["cat", "dog", "rabbit"], "gender": ["neutral"], "personality": ["fluffy", "gentle"], "meaning": "毛茸茸的", "popularity": 8},
    {"name": "Puff", "language": "en", "style": "cute", "species": ["cat", "rabbit"], "gender": ["neutral"], "personality": ["fluffy", "gentle"], "coat_colors": ["white", "cream"], "meaning": "蓬松的小毛球", "popularity": 6},
    {"name": "Fuzzy", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["fluffy", "gentle"], "meaning": "毛茸茸的", "popularity": 5},
    {"name": "Snuggles", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["cuddly", "gentle"], "meaning": "爱撒娇的", "popularity": 6},
    {"name": "Cuddles", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["cuddly", "gentle"], "meaning": "爱拥抱的", "popularity": 6},
    {"name": "Wiggles", "language": "en", "style": "cute", "species": ["dog"], "gender": ["neutral"], "personality": ["happy", "energetic"], "meaning": "扭屁股的小可爱", "popularity": 6},
    {"name": "Bubbles", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["happy", "playful"], "meaning": "泡泡，活泼可爱", "popularity": 7},
    {"name": "Sparkle", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["bright", "energetic"], "meaning": "闪闪发光", "popularity": 6},
    {"name": "Glitter", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["female", "neutral"], "personality": ["bright", "gentle"], "coat_colors": ["silver", "golden"], "meaning": "闪耀", "popularity": 5},
    {"name": "Muffin", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["brown", "cream"], "meaning": "马芬蛋糕，甜美", "popularity": 7},
    {"name": "Cookie", "language": "en", "style": "cute", "species": ["cat", "dog"], "gender": ["neutral"], "personality": ["sweet", "chubby"], "coat_colors": ["brown", "black-white"], "meaning": "曲奇饼干", "popularity": 8},
    {"name": "Biscuit", "language": "en", "style": "cute", "species": ["dog", "cat"], "gender": ["neutral"], "personality": ["sweet", "gentle"], "coat_colors": ["yellow", "cream"], "meaning": "饼干", "popularity": 7},
]


def get_name_entries() -> List[NameEntry]:
    return [NameEntry.from_dict(data) for data in NAMES_DATA]


def init_name_library(storage) -> None:
    existing = storage.load_names()
    if not existing:
        names = get_name_entries()
        storage.save_names(names)
